### ISSUE TITLE
Roadmap/Todos

### ISSUE THREAD

**Issue by Coronon** [Coronon/PySchemeTranspiler#10]
## Immediate (Dev version)
- [x] PyPi package
- [x] While loops (`while True:` should be avoided as `break` and `continue` are not implemented)
- [ ] Dictionaries

#### These features are not set goals!
- [ ] Type checking (`is` keyword?)
- [ ] BitOps ( True | False)
- [ ] Byte literals (`b”Hello”`)
- [ ] Web version (Repl in browser)

### 1.3
- [x] Full tuple support
- [x] Full tuple for loop
- [x] Assert token
- [x] Fix multilevel if-statements
- [x] Remove trailing space in `print(x, ...)`
- [x] Dont print non used function returns
- [x] Escape `"` in constants
- [x] AugAssign (`number += 17`)
- [x] For loop support for Tuple with multiple variables: `for x, y in ((1, 2)):`
- [x] `in` token as in `if "a" in ["a", "b"]:`
- [x] MultiAssign list element swap (`seq[n - 1], seq[n] = seq[n], seq[n - 1]`)
- [x] Toogle for `(define (main) {Usercode})` to allow easier function (module) exports
- [x] Define `__name__` as `"__main__"`
- [x] Add own type to type converters (`int(1)`)

## 1.2
- [x] If-expressions (IfExp) (not `if a == b:`)
- [x] Safe return detection in control structures + warnings and explanation
- [x] Default `return None` + warning
- [x] Support plain `return`
